### ISSUE TITLE
About this website page

### ISSUE THREAD

**Issue by joostf** [fdnd-agency/cmd#40]

**Comment by joostf** [comment]
Sounds perfectly fine to me!

**Comment by irenekamp** [comment]
Ik heb de tekst ook naar Andre gestuurd (omdat ik zijn naam eronder heb gezet), maar misschien kun je kijken of dit voldoende info is, of dat er nog meer achtergrond info over de ontwikkeling in moet:

![image](https://user-images.githubusercontent.com/50575576/189863867-76989729-2ec7-4512-a82d-227a481ba276.png)

**Comment by irenekamp** [comment]
updated versie van Andre:
De midterm review 2022 willen we graag inzetten om feedback te krijgen op ons onderwijs en met het panel te kijken naar de toekomst van het vakgebied en ontwerp-onderwijs. Deze website beschrijft het onderwijs bij CMD Amsterdam, onze kritische reflectie hierop en ambities voor de toekomst.

CMD Amsterdam is een leergemeenschap waarbij studenten, docenten en medewerkers met en van elkaar leren. Deze site is daar ook een voorbeeld van: de inhoud is verzorgd door docenten en medewerkers (Diantha Kinkhouwers, Laura van der Vlies, David de Vries, Jos Kok, Arif Khan, Michel Alders, Tatjana Finke en Zuzana van Polen) en het ontwerp is gemaakt door studenten van CMD Agency (Alana Eastman, Ryan Zoeters, Nina Rijntjes en Pip Harsveld), de minor Web development (Fabienne van den Steen, Kai van Wezel en Nathan Bommezijn) van CMD Amsterdam en Justin Lung (AD Frontend Design en Development, HvA) onder begeleiding van Joost Faber (docent), alles overzien door onze hoofddocent Irene Kamp.

We kijken uit naar de gesprekken op 4 oktober,

Andre Neumann - opleidingsmanager
