### ISSUE TITLE
minor content fixes

### ISSUE THREAD

**Issue by irenekamp** [fdnd-agency/cmd#47]
**homepage**
paragraaf 2.9 en 3.5 > dilemma's ipv Dilemma's

**standaard 1**
1.1 delete laatste zin "Om een beeld te krijgen wat voor producten onze studenten maken bekijk hier de voorbeelden."
1.4 eerste paragraaf "Ook krijgt toegankelijkheid en duurzaamheid van digitale producten aandacht in vakken en projecten." > krijgt moet krijgen worden
1.4 tweede paragraaf "CMD Amsterdam is een van de meest technische CMD opleiding van.." > CMD opleidingen
1.5 ambities tweede punt  "Dit update is erop gericht om" > Deze update

**standaard 2**
2.3 lijkt nog een verkeerde paragraaf te zijn, dit is de juiste: 
2.3 Borging onderwijskwaliteit
De kwaliteit van het onderwijs en van de opleiding wordt op verschillende manieren gewaarborgd. Elk vak wordt door studenten geëvalueerd met een anonieme vragenlijst, waarin wordt gevraagd naar onder meer de verwachtingen, de sfeer, de kwaliteit van de feedback, de toetsing en de didactische vaardigheden van de docent. Ook krijgen studenten de ruimte om te vertellen wat ze goed en minder goed aan het vak vinden. Door ook naar gegevens over studierendement en slagingspercentages te kijken, krijgen we een goed beeld hoe het de studenten vergaat tijdens de opleiding. Deze gegevens worden meegenomen in de vak/project evaluaties die gebruikt worden ter verbetering van de onderwijsmodules.

Naast de vakevaluaties vullen studenten ook enkele bredere enquêtes in; de NSE (Nationale Studentenenquête), de 100dagenmonitor voor eerstejaars, de EXIT-monitor voor studenten die stoppen met de opleiding en de HBO-monitor voor alumni. Al deze evaluaties zijn waardevolle bronnen voor de opleiding. Naast deze grotendeels kwantitatieve bronnen van informatie gebruiken we ook kwalitatieve data. Dit gebeurt onder andere door zogenoemde sense-making sessies met studenten en docenten en door de ruime mogelijkheden van studenten om open feedback te geven. Daarnaast zijn we van plan om (meer) panelgesprekken met studenten te organiseren en peerfeedback onder docenten te faciliteren.

Docenten evalueren in teams hun onderwijseenheden waarbij de feedback van studenten meegenomen wordt in aanpassingen voor volgende keer. Daarnaast blijven docenten up-to-date door het bezoeken van conferenties, andere opleidingen in binnen- en buitenland, workshops, en opleidingen. Ook werken veel docenten parttime bij CMD en daarnaast in het werkveld. Op deze manier blijft ook de inhoud van de vakken en projecten up-to-date.
-----
2.4 kopje Gastcolleges > komma kan weg
2.4 onder "opleidingsadviesraad", een na laatste zin staat <tabel invoegen> > dit is een link geworden: De huidige samenstelling van de OAR is hier https://www.cmd-amsterdam.nl/industry/recap-cmd-advisory-board-1/ te bekijken.
2.7 derde paragraaf 2e zin werkwoord ontbreekt > en "krachten" en deze te benutten.
2.7 paragraaf SLB eerste twee zinnen > ...belangrijke informatie over de studie, wordt de planning doorgenomen... ("wordt" toevoegen) en "... die klassikale bijeenkomsten en individuele gesprekken verzorgt" (ipv verzorgd)
2.7 heading studentendecaan is niet bold

**standaard 3**
3.1 in opsomming punt 1 > de voor student "We geven de student regie over het eigen leerpad"
3.2 derde paragraaf eerste zin ipv continue > continu

**standaard 4**
4.1 paragraaf na de eerste opsomming, de eerste zin"Het ingeleverde werk..." hier ontbreekt een woord > "...die op bepaalde momenten feedback geeft" (geeft toevoegen). 
4.1 paragraaf na de eerste opsomming tweede zin "Dit is een nieuwe beoordelaar..." > De derde lezer is een nieuwe beoordelaar...
4.1 laatste paragraaf eerste zin > spatie voor "De" weghalen
4.2 afbeelding is vrij klein: is het mogelijk te vergroten door op te klikken (of openen in nieuw window?

**Comment by joostf** [comment]
Fixed
